spring:
  profiles: default
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:local
    username: sa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    throw-exception-if-no-handler-found: true
#    static-path-pattern: /static
  resources:
    add-mappings: false
info:
  build: N/A
management:
  endpoint:
    health:
      show-components: ALWAYS
    restart:
      enabled: true
    beans:
      cache:
        time-to-live: 10s
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics'
javax:
  persistent:
    schema-generation:
      create-source: meta-data
      scripts:
        action: create
        create-target: ./create.sql
server:
  tomcat:
    max-threads: 10
    accept-count: 100
    max-connections: 1000
#hibernate:
#  cache:
#    use_second_level_cache: true
#    region:
#      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
logging:
  level:
    com:
      code:
        i: INFO
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web:
          servlet:
            PageNotFound: ERROR
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE